### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by skyguy2002** [jramsgz/traefik-real-ip#3]
My traefik.yml looks like this:

`experimental:
  plugins:
    traefik-real-ip:
      modulename: github.com/jramsgz/traefik-real-ip
      version: v1.0.6
`

My middleware.yml looks like this:

`http:
  middlewares:
    traefik-real-ip:
      plugin:
        traefik-real-ip:
          excludednets:
            - "1.1.1.1/24"`
            
and the service file like this:

`http:
  routers:
    traefik:
      entryPoints:
      -  websecure
      middlewares:
      - traefik-real-ip
      tls: {}
      service: api@internal
      rule: "Host(`traefik.domain.de`)"`

nevertheless it still shows an IP from Cloudflare under the access log, what have I done wrong ?

Acces Log: 

`1.33 - jan [15/Nov/2023:19:33:20 +0000] "GET /dashboard/css/6d73c73c.9b22e80f.css HTTP/2.0" 200 378 "-" "-" 633 "traefik@file" "-" 0ms
172.69.151.116 - jan [15/Nov/2023:19:33:20 +0000] "GET /dashboard/css/52875482.9b22e80f.css HTTP/2.0" 200 378 "-" "-" 634 "traefik@file" "-" 0ms
172.69.151.56 - jan [15/Nov/2023:19:33:20 +0000] "GET /dashboard/js/4d42dcea.18f43827.js HTTP/2.0" 200 39952 "-" "-" 635 "traefik@file" "-" 1ms
172.69.150.207 - jan [15/Nov/2023:19:33:20 +0000] "GET /dashboard/css/797e4f23.9b22e80f.css HTTP/2.0" 200 378 "-" "-" 636 "traefik@file" "-" 0ms
172.69.150.111 - jan [15/Nov/2023:19:33:20 +0000] "GET /dashboard/css/e036c7dc.1666b9a0.css HTTP/2.0" 200 2871 "-" "-" 637 "traefik@file" "-" 0ms
172.69.150.224 - jan [15/Nov/2023:19:33:20 +0000] "GET /dashboard/js/b34404c8.7a4b9be8.js HTTP/2.0" 200 6917 "-" "-" 638 "traefik@file" "-" 0ms
172.69.150.119 - jan [15/Nov/2023:19:33:20 +0000] "GET /dashboard/js/067758be.c7890581.js HTTP/2.0" 200 11437 "-" "-" 639 "traefik@file" "-" 1ms
172.69.151.218 - jan [15/Nov/2023:19:33:21 +0000] "GET /dashboard/css/491024e9.9b22e80f.css HTTP/2.0" 200 378 "-" "-" 640 "traefik@file" "-" 0ms`

**Comment by jramsgz** [comment]
Have you added Cloudflare's IPs to your Traefik's "trustedIPs" config?
Here are their IP ranges: https://www.cloudflare.com/ips/

I think you need to add them to your config so that traefik trusts the header that contains the real IP

Here is an example:
```
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: false
      trustedIPs:
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
 
```
You can check the traefik documentation for that here: https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
